# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stacking-training.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stacking-training.proto',
  package='stacking',
  syntax='proto3',
  serialized_options=b'\n\022com.vhive.stackingB\010stackingP\001Z\035tests/stacking-training/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17stacking-training.proto\x12\x08stacking\"L\n\x0cTrainRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\x0c\x12\x15\n\rdataset_s3key\x18\x02 \x01(\t\x12\x14\n\x0cmodel_config\x18\x03 \x01(\x0c\">\n\nTrainReply\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x13\n\x0bmodel_s3key\x18\x02 \x01(\t\x12\x0c\n\x04pred\x18\x03 \x01(\x0c\"2\n\rReduceRequest\x12\x13\n\x0bmodel_s3key\x18\x01 \x03(\t\x12\x0c\n\x04pred\x18\x02 \x03(\x0c\"J\n\x0bReduceReply\x12\x0e\n\x06models\x18\x01 \x01(\x0c\x12\x14\n\x0cmodels_s3key\x18\x02 \x01(\t\x12\x15\n\rmeta_features\x18\x03 \x01(\x0c\"`\n\x10MetaTrainRequest\x12\x0f\n\x07\x64\x61taset\x18\x01 \x01(\x0c\x12\x15\n\rdataset_s3key\x18\x02 \x01(\t\x12\x0e\n\x06models\x18\x03 \x01(\x0c\x12\x14\n\x0cmodels_s3key\x18\x04 \x01(\t\"`\n\x0eMetaTrainReply\x12\x12\n\nmodel_full\x18\x01 \x01(\x0c\x12\x18\n\x10model_full_s3key\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\t\x12\x11\n\tmeta_pred\x18\x04 \x01(\x0c\x32\x42\n\x07Trainer\x12\x37\n\x05Train\x12\x16.stacking.TrainRequest\x1a\x14.stacking.TrainReply\"\x00\x32\x45\n\x07Reducer\x12:\n\x06Reduce\x12\x17.stacking.ReduceRequest\x1a\x15.stacking.ReduceReply\"\x00\x32R\n\x0bMetaTrainer\x12\x43\n\tMetaTrain\x12\x1a.stacking.MetaTrainRequest\x1a\x18.stacking.MetaTrainReply\"\x00\x42?\n\x12\x63om.vhive.stackingB\x08stackingP\x01Z\x1dtests/stacking-training/protob\x06proto3'
)




_TRAINREQUEST = _descriptor.Descriptor(
  name='TrainRequest',
  full_name='stacking.TrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='stacking.TrainRequest.dataset', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_s3key', full_name='stacking.TrainRequest.dataset_s3key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_config', full_name='stacking.TrainRequest.model_config', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=113,
)


_TRAINREPLY = _descriptor.Descriptor(
  name='TrainReply',
  full_name='stacking.TrainReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='stacking.TrainReply.model', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_s3key', full_name='stacking.TrainReply.model_s3key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pred', full_name='stacking.TrainReply.pred', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=177,
)


_REDUCEREQUEST = _descriptor.Descriptor(
  name='ReduceRequest',
  full_name='stacking.ReduceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_s3key', full_name='stacking.ReduceRequest.model_s3key', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pred', full_name='stacking.ReduceRequest.pred', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=229,
)


_REDUCEREPLY = _descriptor.Descriptor(
  name='ReduceReply',
  full_name='stacking.ReduceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='stacking.ReduceReply.models', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models_s3key', full_name='stacking.ReduceReply.models_s3key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta_features', full_name='stacking.ReduceReply.meta_features', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=305,
)


_METATRAINREQUEST = _descriptor.Descriptor(
  name='MetaTrainRequest',
  full_name='stacking.MetaTrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataset', full_name='stacking.MetaTrainRequest.dataset', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset_s3key', full_name='stacking.MetaTrainRequest.dataset_s3key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models', full_name='stacking.MetaTrainRequest.models', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='models_s3key', full_name='stacking.MetaTrainRequest.models_s3key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=403,
)


_METATRAINREPLY = _descriptor.Descriptor(
  name='MetaTrainReply',
  full_name='stacking.MetaTrainReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_full', full_name='stacking.MetaTrainReply.model_full', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_full_s3key', full_name='stacking.MetaTrainReply.model_full_s3key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='stacking.MetaTrainReply.score', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta_pred', full_name='stacking.MetaTrainReply.meta_pred', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=501,
)

DESCRIPTOR.message_types_by_name['TrainRequest'] = _TRAINREQUEST
DESCRIPTOR.message_types_by_name['TrainReply'] = _TRAINREPLY
DESCRIPTOR.message_types_by_name['ReduceRequest'] = _REDUCEREQUEST
DESCRIPTOR.message_types_by_name['ReduceReply'] = _REDUCEREPLY
DESCRIPTOR.message_types_by_name['MetaTrainRequest'] = _METATRAINREQUEST
DESCRIPTOR.message_types_by_name['MetaTrainReply'] = _METATRAINREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainReply = _reflection.GeneratedProtocolMessageType('TrainReply', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREPLY,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.TrainReply)
  })
_sym_db.RegisterMessage(TrainReply)

ReduceRequest = _reflection.GeneratedProtocolMessageType('ReduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _REDUCEREQUEST,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.ReduceRequest)
  })
_sym_db.RegisterMessage(ReduceRequest)

ReduceReply = _reflection.GeneratedProtocolMessageType('ReduceReply', (_message.Message,), {
  'DESCRIPTOR' : _REDUCEREPLY,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.ReduceReply)
  })
_sym_db.RegisterMessage(ReduceReply)

MetaTrainRequest = _reflection.GeneratedProtocolMessageType('MetaTrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _METATRAINREQUEST,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.MetaTrainRequest)
  })
_sym_db.RegisterMessage(MetaTrainRequest)

MetaTrainReply = _reflection.GeneratedProtocolMessageType('MetaTrainReply', (_message.Message,), {
  'DESCRIPTOR' : _METATRAINREPLY,
  '__module__' : 'stacking_training_pb2'
  # @@protoc_insertion_point(class_scope:stacking.MetaTrainReply)
  })
_sym_db.RegisterMessage(MetaTrainReply)


DESCRIPTOR._options = None

_TRAINER = _descriptor.ServiceDescriptor(
  name='Trainer',
  full_name='stacking.Trainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=503,
  serialized_end=569,
  methods=[
  _descriptor.MethodDescriptor(
    name='Train',
    full_name='stacking.Trainer.Train',
    index=0,
    containing_service=None,
    input_type=_TRAINREQUEST,
    output_type=_TRAINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINER)

DESCRIPTOR.services_by_name['Trainer'] = _TRAINER


_REDUCER = _descriptor.ServiceDescriptor(
  name='Reducer',
  full_name='stacking.Reducer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=571,
  serialized_end=640,
  methods=[
  _descriptor.MethodDescriptor(
    name='Reduce',
    full_name='stacking.Reducer.Reduce',
    index=0,
    containing_service=None,
    input_type=_REDUCEREQUEST,
    output_type=_REDUCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDUCER)

DESCRIPTOR.services_by_name['Reducer'] = _REDUCER


_METATRAINER = _descriptor.ServiceDescriptor(
  name='MetaTrainer',
  full_name='stacking.MetaTrainer',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=642,
  serialized_end=724,
  methods=[
  _descriptor.MethodDescriptor(
    name='MetaTrain',
    full_name='stacking.MetaTrainer.MetaTrain',
    index=0,
    containing_service=None,
    input_type=_METATRAINREQUEST,
    output_type=_METATRAINREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METATRAINER)

DESCRIPTOR.services_by_name['MetaTrainer'] = _METATRAINER

# @@protoc_insertion_point(module_scope)
