name: vHive tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GOOS: linux
  GO111MODULE: on

jobs:

  build:
    strategy:
      matrix:
        go: ['1.13', '1.14', '1.15']
      # Build all variants regardless of failures
      fail-fast: false

    name: Build and check code quality
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        # to add commit DCO checks later
        fetch-depth: 21

    - name: Check code
      uses: Jerome1337/golint-action@v1.0.2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Setup Node
      run: source ./scripts/travis/setup_node.sh

    - name: Build
      run: go build -race -v -a ./...

  test-unit:
    name: Unit tests
    runs-on: [self-hosted, ctrd]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run tests in modules
      run: make test-subdirs

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh

  test-e2e:
    name: Integration tests
    runs-on: [self-hosted, ctrd]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run vHive end-to-end tests
      run: make test

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh

  test-e2e-manual:
    name: Integration tests (with manual cleaning)
    runs-on: [self-hosted, ctrd]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run vHive tests that need manual cleaning
      run: make test-man-bench

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh
